// Generated by scripts/generate-catalog.ts — do not edit manually
import { CreateAddonCommand } from "@clevercloud/client/cc-api-commands/addon/create-addon-command.js";
import { DeleteAddonCommand } from "@clevercloud/client/cc-api-commands/addon/delete-addon-command.js";
import { GetAddonCommand } from "@clevercloud/client/cc-api-commands/addon/get-addon-command.js";
import { GetAddonSsoCommand } from "@clevercloud/client/cc-api-commands/addon/get-addon-sso-command.js";
import { ListAddonCommand } from "@clevercloud/client/cc-api-commands/addon/list-addon-command.js";
import { UpdateAddonCommand } from "@clevercloud/client/cc-api-commands/addon/update-addon-command.js";
import { CreateAddonProviderCommand } from "@clevercloud/client/cc-api-commands/addon-provider/create-addon-provider-command.js";
import { CreateAddonProviderFeatureCommand } from "@clevercloud/client/cc-api-commands/addon-provider/create-addon-provider-feature-command.js";
import { CreateAddonProviderPlanCommand } from "@clevercloud/client/cc-api-commands/addon-provider/create-addon-provider-plan-command.js";
import { DeleteAddonProviderCommand } from "@clevercloud/client/cc-api-commands/addon-provider/delete-addon-provider-command.js";
import { DeleteAddonProviderFeatureCommand } from "@clevercloud/client/cc-api-commands/addon-provider/delete-addon-provider-feature-command.js";
import { DeleteAddonProviderPlanCommand } from "@clevercloud/client/cc-api-commands/addon-provider/delete-addon-provider-plan-command.js";
import { GetAddonProviderCommand } from "@clevercloud/client/cc-api-commands/addon-provider/get-addon-provider-command.js";
import { ListAddonProviderFeatureCommand } from "@clevercloud/client/cc-api-commands/addon-provider/list-addon-provider-feature-command.js";
import { ListAddonProviderPlanCommand } from "@clevercloud/client/cc-api-commands/addon-provider/list-addon-provider-plan-command.js";
import { UpdateAddonProviderCommand } from "@clevercloud/client/cc-api-commands/addon-provider/update-addon-provider-command.js";
import { UpdateAddonProviderPlanCommand } from "@clevercloud/client/cc-api-commands/addon-provider/update-addon-provider-plan-command.js";
import { CreateApplicationCommand } from "@clevercloud/client/cc-api-commands/application/create-application-command.js";
import { DeleteApplicationCommand } from "@clevercloud/client/cc-api-commands/application/delete-application-command.js";
import { DeployApplicationCommand } from "@clevercloud/client/cc-api-commands/application/deploy-application-command.js";
import { GetApplicationBranchesCommand } from "@clevercloud/client/cc-api-commands/application/get-application-branches-command.js";
import { GetApplicationCommand } from "@clevercloud/client/cc-api-commands/application/get-application-command.js";
import { ListApplicationCommand } from "@clevercloud/client/cc-api-commands/application/list-application-command.js";
import { UndeployApplicationCommand } from "@clevercloud/client/cc-api-commands/application/undeploy-application-command.js";
import { UpdateApplicationCommand } from "@clevercloud/client/cc-api-commands/application/update-application-command.js";
import { ConfirmAuthMfaCommand } from "@clevercloud/client/cc-api-commands/auth/confirm-auth-mfa-command.js";
import { CreateAuthMfaCommand } from "@clevercloud/client/cc-api-commands/auth/create-auth-mfa-command.js";
import { DeleteAuthMfaCommand } from "@clevercloud/client/cc-api-commands/auth/delete-auth-mfa-command.js";
import { GetAuthMfaBackupCodesCommand } from "@clevercloud/client/cc-api-commands/auth/get-auth-mfa-backup-codes-command.js";
import { UpdateAuthPasswordCommand } from "@clevercloud/client/cc-api-commands/auth/update-auth-password-command.js";
import { ListBackupCommand } from "@clevercloud/client/cc-api-commands/backup/list-backup-command.js";
import { GetConfigProviderCommand } from "@clevercloud/client/cc-api-commands/config-provider/get-config-provider-command.js";
import { UpdateConfigProviderCommand } from "@clevercloud/client/cc-api-commands/config-provider/update-config-provider-command.js";
import { ActivateCouponCommand } from "@clevercloud/client/cc-api-commands/credits/activate-coupon-command.js";
import { GetCreditsSummaryCommand } from "@clevercloud/client/cc-api-commands/credits/get-credits-summary-command.js";
import { CancelDeploymentCommand } from "@clevercloud/client/cc-api-commands/deployment/cancel-deployment-command.js";
import { GetDeploymentCommand } from "@clevercloud/client/cc-api-commands/deployment/get-deployment-command.js";
import { ListDeploymentCommand } from "@clevercloud/client/cc-api-commands/deployment/list-deployment-command.js";
import { CreateDomainCommand } from "@clevercloud/client/cc-api-commands/domain/create-domain-command.js";
import { DeleteDomainCommand } from "@clevercloud/client/cc-api-commands/domain/delete-domain-command.js";
import { GetPrimaryDomainCommand } from "@clevercloud/client/cc-api-commands/domain/get-primary-domain-command.js";
import { ListDomainCommand } from "@clevercloud/client/cc-api-commands/domain/list-domain-command.js";
import { SetPrimaryDomainCommand } from "@clevercloud/client/cc-api-commands/domain/set-primary-domain-command.js";
import { UnsetPrimaryDomainCommand } from "@clevercloud/client/cc-api-commands/domain/unset-primary-domain-command.js";
import { GetElasticsearchInfoCommand } from "@clevercloud/client/cc-api-commands/elasticsearch/get-elasticsearch-info-command.js";
import { CreateOrUpdateEnvironmentVariableCommand } from "@clevercloud/client/cc-api-commands/environment/create-or-update-environment-variable-command.js";
import { DeleteEnvironmentVariableCommand } from "@clevercloud/client/cc-api-commands/environment/delete-environment-variable-command.js";
import { GetEnvironmentCommand } from "@clevercloud/client/cc-api-commands/environment/get-environment-command.js";
import { GetExposedEnvironmentCommand } from "@clevercloud/client/cc-api-commands/environment/get-exposed-environment-command.js";
import { UpdateEnvironmentCommand } from "@clevercloud/client/cc-api-commands/environment/update-environment-command.js";
import { UpdateExposedEnvironmentCommand } from "@clevercloud/client/cc-api-commands/environment/update-exposed-environment-command.js";
import { GetGithubLinkTransactionIdCommand } from "@clevercloud/client/cc-api-commands/github/get-github-link-transaction-id-command.js";
import { GetGithubUsernameCommand } from "@clevercloud/client/cc-api-commands/github/get-github-username-command.js";
import { ListGithubApplicationCommand } from "@clevercloud/client/cc-api-commands/github/list-github-application-command.js";
import { UnlinkGithubAccountCommand } from "@clevercloud/client/cc-api-commands/github/unlink-github-account-command.js";
import { DisableGrafanaCommand } from "@clevercloud/client/cc-api-commands/grafana/disable-grafana-command.js";
import { EnableGrafanaCommand } from "@clevercloud/client/cc-api-commands/grafana/enable-grafana-command.js";
import { GetGrafanaCommand } from "@clevercloud/client/cc-api-commands/grafana/get-grafana-command.js";
import { ResetGrafanaCommand } from "@clevercloud/client/cc-api-commands/grafana/reset-grafana-command.js";
import { GetHeptapodPriceEstimationCommand } from "@clevercloud/client/cc-api-commands/heptapod/get-heptapod-price-estimation-command.js";
import { GetApplicationInstanceCommand } from "@clevercloud/client/cc-api-commands/instance/get-application-instance-command.js";
import { ListApplicationInstanceCommand } from "@clevercloud/client/cc-api-commands/instance/list-application-instance-command.js";
import { GetInvoiceCommand } from "@clevercloud/client/cc-api-commands/invoice/get-invoice-command.js";
import { GetInvoiceHtmlCommand } from "@clevercloud/client/cc-api-commands/invoice/get-invoice-html-command.js";
import { GetInvoicePdfCommand } from "@clevercloud/client/cc-api-commands/invoice/get-invoice-pdf-command.js";
import { ListInvoiceCommand } from "@clevercloud/client/cc-api-commands/invoice/list-invoice-command.js";
import { ListUnpaidInvoiceCommand } from "@clevercloud/client/cc-api-commands/invoice/list-unpaid-invoice-command.js";
import { GetJenkinsInfoCommand } from "@clevercloud/client/cc-api-commands/jenkins/get-jenkins-info-command.js";
import { AddLinkCommand } from "@clevercloud/client/cc-api-commands/link/add-link-command.js";
import { AddApplicationToApplicationLinkCommand } from "@clevercloud/client/cc-api-commands/link/add-link-command.js";
import { AddApplicationToAddonLinkCommand } from "@clevercloud/client/cc-api-commands/link/add-link-command.js";
import { ListLinkCommand } from "@clevercloud/client/cc-api-commands/link/list-link-command.js";
import { RemoveLinkCommand } from "@clevercloud/client/cc-api-commands/link/remove-link-command.js";
import { RemoveApplicationToApplicationLinkCommand } from "@clevercloud/client/cc-api-commands/link/remove-link-command.js";
import { RemoveApplicationToAddonLinkCommand } from "@clevercloud/client/cc-api-commands/link/remove-link-command.js";
import { GetLoadBalancerInfoCommand } from "@clevercloud/client/cc-api-commands/load-balancer/get-load-balancer-info-command.js";
import { ListLogCommand } from "@clevercloud/client/cc-api-commands/log/list-log-command.js";
import { StreamAddonRuntimeLogCommand } from "@clevercloud/client/cc-api-commands/log/stream-addon-runtime-log-command.js";
import { StreamApplicationAccessLogCommand } from "@clevercloud/client/cc-api-commands/log/stream-application-access-log-command.js";
import { StreamApplicationRuntimeLogCommand } from "@clevercloud/client/cc-api-commands/log/stream-application-runtime-log-command.js";
import { CreateLogDrainCommand } from "@clevercloud/client/cc-api-commands/log-drain/create-log-drain-command.js";
import { DeleteLogDrainCommand } from "@clevercloud/client/cc-api-commands/log-drain/delete-log-drain-command.js";
import { DisableLogDrainCommand } from "@clevercloud/client/cc-api-commands/log-drain/disable-log-drain-command.js";
import { EnableLogDrainCommand } from "@clevercloud/client/cc-api-commands/log-drain/enable-log-drain-command.js";
import { GetLogDrainCommand } from "@clevercloud/client/cc-api-commands/log-drain/get-log-drain-command.js";
import { ListLogDrainCommand } from "@clevercloud/client/cc-api-commands/log-drain/list-log-drain-command.js";
import { GetMateriaInfoCommand } from "@clevercloud/client/cc-api-commands/materia/get-materia-info-command.js";
import { GetMatomoInfoCommand } from "@clevercloud/client/cc-api-commands/matomo/get-matomo-info-command.js";
import { GetMetricsCommand } from "@clevercloud/client/cc-api-commands/metrics/get-metrics-command.js";
import { CancelMigrationCommand } from "@clevercloud/client/cc-api-commands/migration/cancel-migration-command.js";
import { GetMigrationCommand } from "@clevercloud/client/cc-api-commands/migration/get-migration-command.js";
import { ListMigrationCommand } from "@clevercloud/client/cc-api-commands/migration/list-migration-command.js";
import { ListMigrationPreorderCommand } from "@clevercloud/client/cc-api-commands/migration/list-migration-preorder-command.js";
import { StartMigrationCommand } from "@clevercloud/client/cc-api-commands/migration/start-migration-command.js";
import { CreateNetworkGroupCommand } from "@clevercloud/client/cc-api-commands/network-group/create-network-group-command.js";
import { CreateNetworkGroupExternalPeerCommand } from "@clevercloud/client/cc-api-commands/network-group/create-network-group-external-peer-command.js";
import { CreateNetworkGroupMemberCommand } from "@clevercloud/client/cc-api-commands/network-group/create-network-group-member-command.js";
import { DeleteNetworkGroupCommand } from "@clevercloud/client/cc-api-commands/network-group/delete-network-group-command.js";
import { DeleteNetworkGroupExternalPeerCommand } from "@clevercloud/client/cc-api-commands/network-group/delete-network-group-external-peer-command.js";
import { DeleteNetworkGroupMemberCommand } from "@clevercloud/client/cc-api-commands/network-group/delete-network-group-member-command.js";
import { GetNetworkGroupCommand } from "@clevercloud/client/cc-api-commands/network-group/get-network-group-command.js";
import { GetNetworkGroupMemberCommand } from "@clevercloud/client/cc-api-commands/network-group/get-network-group-member-command.js";
import { GetNetworkGroupPeerCommand } from "@clevercloud/client/cc-api-commands/network-group/get-network-group-peer-command.js";
import { GetNetworkGroupWireguardConfigurationCommand } from "@clevercloud/client/cc-api-commands/network-group/get-network-group-wireguard-configuration-command.js";
import { ListNetworkGroupCommand } from "@clevercloud/client/cc-api-commands/network-group/list-network-group-command.js";
import { SearchNetworkGroupCommand } from "@clevercloud/client/cc-api-commands/network-group/search-network-group-command.js";
import { CreateEmailNotificationCommand } from "@clevercloud/client/cc-api-commands/notification/create-email-notification-command.js";
import { CreateWebhookNotificationCommand } from "@clevercloud/client/cc-api-commands/notification/create-webhook-notification-command.js";
import { DeleteEmailNotificationCommand } from "@clevercloud/client/cc-api-commands/notification/delete-email-notification-command.js";
import { DeleteWebhookNotificationCommand } from "@clevercloud/client/cc-api-commands/notification/delete-webhook-notification-command.js";
import { GetNotificationInfoCommand } from "@clevercloud/client/cc-api-commands/notification/get-notification-info-command.js";
import { ListEmailNotificationCommand } from "@clevercloud/client/cc-api-commands/notification/list-email-notification-command.js";
import { ListWebhookNotificationCommand } from "@clevercloud/client/cc-api-commands/notification/list-webhook-notification-command.js";
import { CreateOauthConsumerCommand } from "@clevercloud/client/cc-api-commands/oauth-consumer/create-oauth-consumer-command.js";
import { DeleteOauthConsumerCommand } from "@clevercloud/client/cc-api-commands/oauth-consumer/delete-oauth-consumer-command.js";
import { GetOauthConsumerCommand } from "@clevercloud/client/cc-api-commands/oauth-consumer/get-oauth-consumer-command.js";
import { GetOauthConsumerSecretCommand } from "@clevercloud/client/cc-api-commands/oauth-consumer/get-oauth-consumer-secret-command.js";
import { ListOauthConsumerCommand } from "@clevercloud/client/cc-api-commands/oauth-consumer/list-oauth-consumer-command.js";
import { UpdateOauthConsumerCommand } from "@clevercloud/client/cc-api-commands/oauth-consumer/update-oauth-consumer-command.js";
import { DeleteOauthTokenCommand } from "@clevercloud/client/cc-api-commands/oauth-token/delete-all-oauth-tokens-command.js";
import { ListOauthTokenCommand } from "@clevercloud/client/cc-api-commands/oauth-token/list-oauth-token-command.js";
import { AddOrganisationMemberCommand } from "@clevercloud/client/cc-api-commands/organisation/add-organisation-member-command.js";
import { CreateOrganisationCommand } from "@clevercloud/client/cc-api-commands/organisation/create-organisation-command.js";
import { DeleteOrganisationCommand } from "@clevercloud/client/cc-api-commands/organisation/delete-organisation-command.js";
import { GetOrganisationCommand } from "@clevercloud/client/cc-api-commands/organisation/get-organisation-command.js";
import { GetOrganisationSummariesCommand } from "@clevercloud/client/cc-api-commands/organisation/get-organisation-summaries-command.js";
import { ListOrganisationCommand } from "@clevercloud/client/cc-api-commands/organisation/list-organisation-command.js";
import { ListOrganisationMemberCommand } from "@clevercloud/client/cc-api-commands/organisation/list-organisation-member-command.js";
import { RemoveOrganisationMemberCommand } from "@clevercloud/client/cc-api-commands/organisation/remove-organisation-member-command.js";
import { UpdateOrganisationAvatarCommand } from "@clevercloud/client/cc-api-commands/organisation/update-organisation-avatar-command.js";
import { UpdateOrganisationCommand } from "@clevercloud/client/cc-api-commands/organisation/update-organisation-command.js";
import { UpdateOrganisationMemberCommand } from "@clevercloud/client/cc-api-commands/organisation/update-organisation-member-command.js";
import { AuthorizePaypalCommand } from "@clevercloud/client/cc-api-commands/payment/authorize-paypal-command.js";
import { AuthorizeStripeCommand } from "@clevercloud/client/cc-api-commands/payment/authorize-stripe-command.js";
import { GetStripeIntentCommand } from "@clevercloud/client/cc-api-commands/payment/get-stripe-intent-command.js";
import { InitPaypalCommand } from "@clevercloud/client/cc-api-commands/payment/init-paypal-command.js";
import { InitStripeCommand } from "@clevercloud/client/cc-api-commands/payment/init-stripe-command.js";
import { CreatePaymentMethodCommand } from "@clevercloud/client/cc-api-commands/payment-method/create-payment-method-command.js";
import { DeletePaymentMethodCommand } from "@clevercloud/client/cc-api-commands/payment-method/delete-payment-method-command.js";
import { ListPaymentMethodCommand } from "@clevercloud/client/cc-api-commands/payment-method/list-payment-method-command.js";
import { SetPrimaryPaymentMethodCommand } from "@clevercloud/client/cc-api-commands/payment-method/set-primary-payment-method-command.js";
import { GetPriceSystemCommand } from "@clevercloud/client/cc-api-commands/price-system/get-price-system-command.js";
import { GetProductAddonCommand } from "@clevercloud/client/cc-api-commands/product/get-product-addon-command.js";
import { GetProductAddonVersionsCommand } from "@clevercloud/client/cc-api-commands/product/get-product-addon-versions-command.js";
import { GetProductElasticsearchInfoCommand } from "@clevercloud/client/cc-api-commands/product/get-product-elasticsearch-info-command.js";
import { GetProductRuntimeCommand } from "@clevercloud/client/cc-api-commands/product/get-product-runtime-command.js";
import { ListProductAddonCommand } from "@clevercloud/client/cc-api-commands/product/list-product-addon-command.js";
import { ListProductRuntimeCommand } from "@clevercloud/client/cc-api-commands/product/list-product-runtime-command.js";
import { CreateProfileEmailAddressCommand } from "@clevercloud/client/cc-api-commands/profile/create-profile-email-address-command.js";
import { DeleteProfileEmailAddressCommand } from "@clevercloud/client/cc-api-commands/profile/delete-profile-email-address-command.js";
import { GetProfileCommand } from "@clevercloud/client/cc-api-commands/profile/get-profile-command.js";
import { ListProfileEmailAddressCommand } from "@clevercloud/client/cc-api-commands/profile/list-profile-email-address-command.js";
import { RequestProfileEmailConfirmationCommand } from "@clevercloud/client/cc-api-commands/profile/request-profile-email-confirmation-command.js";
import { SetProfilePrimaryEmailAddressCommand } from "@clevercloud/client/cc-api-commands/profile/set-profile-primary-email-address-command.js";
import { UpdateProfileAvatarCommand } from "@clevercloud/client/cc-api-commands/profile/update-profile-avatar-command.js";
import { UpdateProfileCommand } from "@clevercloud/client/cc-api-commands/profile/update-profile-command.js";
import { GetPulsarInfoCommand } from "@clevercloud/client/cc-api-commands/pulsar/get-pulsar-info-command.js";
import { CreatePersonalSshKeyCommand } from "@clevercloud/client/cc-api-commands/ssh-key/create-personal-ssh-key-command.js";
import { DeletePersonalSshKeyCommand } from "@clevercloud/client/cc-api-commands/ssh-key/delete-personal-ssh-key-command.js";
import { ListGithubSshKeyCommand } from "@clevercloud/client/cc-api-commands/ssh-key/list-github-ssh-key-command.js";
import { ListPersonalSshKeyCommand } from "@clevercloud/client/cc-api-commands/ssh-key/list-personal-ssh-key-command.js";
import { CreateTagCommand } from "@clevercloud/client/cc-api-commands/tag/create-tag-command.js";
import { DeleteTagCommand } from "@clevercloud/client/cc-api-commands/tag/delete-tag-command.js";
import { ListTagCommand } from "@clevercloud/client/cc-api-commands/tag/list-tag-command.js";
import { UpdateTagCommand } from "@clevercloud/client/cc-api-commands/tag/update-tag-command.js";
import { CreateTcpRedirectionCommand } from "@clevercloud/client/cc-api-commands/tcp-redirection/create-tcp-redirection-command.js";
import { DeleteTcpRedirectionCommand } from "@clevercloud/client/cc-api-commands/tcp-redirection/delete-tcp-redirection-command.js";
import { ListTcpRedirectionCommand } from "@clevercloud/client/cc-api-commands/tcp-redirection/list-tcp-redirection-command.js";
import { ListTcpRedirectionNamespaceCommand } from "@clevercloud/client/cc-api-commands/tcp-redirection/list-tcp-redirection-namespace-command.js";
import { DeleteUserSettingCommand } from "@clevercloud/client/cc-api-commands/user-setting/delete-user-setting-command.js";
import { GetUserSettingCommand } from "@clevercloud/client/cc-api-commands/user-setting/get-user-setting-command.js";
import { SetUserSettingCommand } from "@clevercloud/client/cc-api-commands/user-setting/set-user-setting-command.js";
import { CheckVatNumberCommand } from "@clevercloud/client/cc-api-commands/vat-number/check-vat-number-command.js";
import { GetWarpTokenCommand } from "@clevercloud/client/cc-api-commands/warp-token/get-warp-token-command.js";
import { GetZoneCommand } from "@clevercloud/client/cc-api-commands/zone/get-zone-command.js";
import { ListZoneCommand } from "@clevercloud/client/cc-api-commands/zone/list-zone-command.js";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const commands: Record<string, new (params?: any) => any> = {
  CreateAddonCommand,
  DeleteAddonCommand,
  GetAddonCommand,
  GetAddonSsoCommand,
  ListAddonCommand,
  UpdateAddonCommand,
  CreateAddonProviderCommand,
  CreateAddonProviderFeatureCommand,
  CreateAddonProviderPlanCommand,
  DeleteAddonProviderCommand,
  DeleteAddonProviderFeatureCommand,
  DeleteAddonProviderPlanCommand,
  GetAddonProviderCommand,
  ListAddonProviderFeatureCommand,
  ListAddonProviderPlanCommand,
  UpdateAddonProviderCommand,
  UpdateAddonProviderPlanCommand,
  CreateApplicationCommand,
  DeleteApplicationCommand,
  DeployApplicationCommand,
  GetApplicationBranchesCommand,
  GetApplicationCommand,
  ListApplicationCommand,
  UndeployApplicationCommand,
  UpdateApplicationCommand,
  ConfirmAuthMfaCommand,
  CreateAuthMfaCommand,
  DeleteAuthMfaCommand,
  GetAuthMfaBackupCodesCommand,
  UpdateAuthPasswordCommand,
  ListBackupCommand,
  GetConfigProviderCommand,
  UpdateConfigProviderCommand,
  ActivateCouponCommand,
  GetCreditsSummaryCommand,
  CancelDeploymentCommand,
  GetDeploymentCommand,
  ListDeploymentCommand,
  CreateDomainCommand,
  DeleteDomainCommand,
  GetPrimaryDomainCommand,
  ListDomainCommand,
  SetPrimaryDomainCommand,
  UnsetPrimaryDomainCommand,
  GetElasticsearchInfoCommand,
  CreateOrUpdateEnvironmentVariableCommand,
  DeleteEnvironmentVariableCommand,
  GetEnvironmentCommand,
  GetExposedEnvironmentCommand,
  UpdateEnvironmentCommand,
  UpdateExposedEnvironmentCommand,
  GetGithubLinkTransactionIdCommand,
  GetGithubUsernameCommand,
  ListGithubApplicationCommand,
  UnlinkGithubAccountCommand,
  DisableGrafanaCommand,
  EnableGrafanaCommand,
  GetGrafanaCommand,
  ResetGrafanaCommand,
  GetHeptapodPriceEstimationCommand,
  GetApplicationInstanceCommand,
  ListApplicationInstanceCommand,
  GetInvoiceCommand,
  GetInvoiceHtmlCommand,
  GetInvoicePdfCommand,
  ListInvoiceCommand,
  ListUnpaidInvoiceCommand,
  GetJenkinsInfoCommand,
  AddLinkCommand,
  AddApplicationToApplicationLinkCommand,
  AddApplicationToAddonLinkCommand,
  ListLinkCommand,
  RemoveLinkCommand,
  RemoveApplicationToApplicationLinkCommand,
  RemoveApplicationToAddonLinkCommand,
  GetLoadBalancerInfoCommand,
  ListLogCommand,
  StreamAddonRuntimeLogCommand,
  StreamApplicationAccessLogCommand,
  StreamApplicationRuntimeLogCommand,
  CreateLogDrainCommand,
  DeleteLogDrainCommand,
  DisableLogDrainCommand,
  EnableLogDrainCommand,
  GetLogDrainCommand,
  ListLogDrainCommand,
  GetMateriaInfoCommand,
  GetMatomoInfoCommand,
  GetMetricsCommand,
  CancelMigrationCommand,
  GetMigrationCommand,
  ListMigrationCommand,
  ListMigrationPreorderCommand,
  StartMigrationCommand,
  CreateNetworkGroupCommand,
  CreateNetworkGroupExternalPeerCommand,
  CreateNetworkGroupMemberCommand,
  DeleteNetworkGroupCommand,
  DeleteNetworkGroupExternalPeerCommand,
  DeleteNetworkGroupMemberCommand,
  GetNetworkGroupCommand,
  GetNetworkGroupMemberCommand,
  GetNetworkGroupPeerCommand,
  GetNetworkGroupWireguardConfigurationCommand,
  ListNetworkGroupCommand,
  SearchNetworkGroupCommand,
  CreateEmailNotificationCommand,
  CreateWebhookNotificationCommand,
  DeleteEmailNotificationCommand,
  DeleteWebhookNotificationCommand,
  GetNotificationInfoCommand,
  ListEmailNotificationCommand,
  ListWebhookNotificationCommand,
  CreateOauthConsumerCommand,
  DeleteOauthConsumerCommand,
  GetOauthConsumerCommand,
  GetOauthConsumerSecretCommand,
  ListOauthConsumerCommand,
  UpdateOauthConsumerCommand,
  DeleteOauthTokenCommand,
  ListOauthTokenCommand,
  AddOrganisationMemberCommand,
  CreateOrganisationCommand,
  DeleteOrganisationCommand,
  GetOrganisationCommand,
  GetOrganisationSummariesCommand,
  ListOrganisationCommand,
  ListOrganisationMemberCommand,
  RemoveOrganisationMemberCommand,
  UpdateOrganisationAvatarCommand,
  UpdateOrganisationCommand,
  UpdateOrganisationMemberCommand,
  AuthorizePaypalCommand,
  AuthorizeStripeCommand,
  GetStripeIntentCommand,
  InitPaypalCommand,
  InitStripeCommand,
  CreatePaymentMethodCommand,
  DeletePaymentMethodCommand,
  ListPaymentMethodCommand,
  SetPrimaryPaymentMethodCommand,
  GetPriceSystemCommand,
  GetProductAddonCommand,
  GetProductAddonVersionsCommand,
  GetProductElasticsearchInfoCommand,
  GetProductRuntimeCommand,
  ListProductAddonCommand,
  ListProductRuntimeCommand,
  CreateProfileEmailAddressCommand,
  DeleteProfileEmailAddressCommand,
  GetProfileCommand,
  ListProfileEmailAddressCommand,
  RequestProfileEmailConfirmationCommand,
  SetProfilePrimaryEmailAddressCommand,
  UpdateProfileAvatarCommand,
  UpdateProfileCommand,
  GetPulsarInfoCommand,
  CreatePersonalSshKeyCommand,
  DeletePersonalSshKeyCommand,
  ListGithubSshKeyCommand,
  ListPersonalSshKeyCommand,
  CreateTagCommand,
  DeleteTagCommand,
  ListTagCommand,
  UpdateTagCommand,
  CreateTcpRedirectionCommand,
  DeleteTcpRedirectionCommand,
  ListTcpRedirectionCommand,
  ListTcpRedirectionNamespaceCommand,
  DeleteUserSettingCommand,
  GetUserSettingCommand,
  SetUserSettingCommand,
  CheckVatNumberCommand,
  GetWarpTokenCommand,
  GetZoneCommand,
  ListZoneCommand,
};
